[project]
name = "fedgenie3"
version = "0.1.0"
description = "A federated version of GENIE3."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "scikit-learn>=1.5.2",
    "pydantic>=2.9.2",
    "typer>=0.12.5",
    "loguru>=0.7.2",
    "pytest>=8.3.3",
    "synapseclient>=4.5.1",
    "invoke>=2.2.0",
    "flwr>=1.7.0",
    "pandas>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
