data:
  gene_expressions_path: "local_data/processed/dream_five/net1_in-silico/gene_expression_data.tsv"
  transcription_factors_path: "local_data/processed/dream_five/net1_in-silico/transcription_factors.tsv"
  reference_network_path: 

regressor:
  name: "RandomForestRegressor"
  init_params:
    n_estimators: 100
    random_state: 42
    n_jobs: 8
    max_depth: 4
    max_features: 0.8
    bootstrap: True