data:
  gene_expressions_path: "local_data/processed/dream_five/net1_in-silico/gene_expression_data.tsv"
  transcription_factors_path: "local_data/processed/dream_five/net1_in-silico/transcription_factors.tsv"
  reference_network_path: "local_data/processed/dream_five/net1_in-silico/reference_network_data.tsv"

regressor:
  name: "XGB"
  init_params:
    objective: "reg:squarederror"
    tree_method: "hist"
    feature_selector: "random"
    learning_rate: 0.01
    max_depth: 3
    seed: 42
    verbosity: 0
    n_jobs: 8
    device: "cpu"
  fit_params:
    verbose_eval: False
    num_boost_round: 1000
    early_stopping_rounds: 10
